server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver